variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 4

stages:
  - everything

debian:
  stage: everything
  image: debian:stable
  before_script:
    - apt-get update
    - apt-get install -y curl build-essential gcc make clangd clang
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source "$HOME/.cargo/env"
    - rustup component add rust-analyzer
    - echo $PATH | grep cargo
    - which rust-analyzer
    - rust-analyzer --help
  script:
    - cargo build
    - cargo test show_usages_integ_test_1_INCOMPLETE -- --nocapture
    - cargo test
    - cargo fmt --check
  artifacts:
    paths:
      - "clang*"
      - "screenshots"
    when: always

