variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 4

stages:
  - everything

debian:
  stage: everything
  image: rust:1-bookworm
  before_script:
    - apt-get update
    - apt-get install -y curl build-essential gcc make clangd clang
    - rustup component add rustfmt
    - rustup component add rust-analyzer
    - which rust-analyzer
    - curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
  script:
    - cargo build
    # it takes ages to compile and ALL tests run under 60 seconds, so I want to get full results
    - cargo nextest run --no-fail-fast --retries 4
    - cargo fmt --check
  artifacts:
    paths:
      - "clang*"
      - "screenshots"
    when: always

