variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 4
  GIT_DEPTH: 10

stages:
  - setup
  - build
  - test

install_rust_analyzer:
  stage: setup
  image: rust:latest
  script:
    - 'if ! command -v rust-analyzer &> /dev/null; then cargo install ra_ap_rust-analyzer; fi'
  only:
    - branches

rust-latest-build:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose --release
  artifacts:
    paths:
      - target/release/bernardo
    expire_in: 1 day

rust-latest-test:
  stage: test
  image: rust:latest
  script:
    - cargo test --verbose
    - rm -rf target/
  dependencies:
    - rust-latest-build

rust-nightly-build:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose --release

rust-nightly-test:
  stage: test
  image: rustlang/rust:nightly
  script:
    - cargo test --verbose
    - rm -rf target/
  dependencies:
    - rust-nightly-build
