variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 4

stages:
  - everything

debian:
  stage: everything
  image: rust:bookworm
  before_script:
    - apt-get update
    - apt-get install -y curl build-essential gcc make clangd clang
    #    - rustup component add rust-analyzer
    - rustup component add rustfmt
    #    - echo $PATH | grep cargo
    #    - which rust-analyzer
    #    - rust-analyzer --help
  script:
    - cargo build
    - cargo test
    - cargo fmt --check
  artifacts:
    paths:
      - "clang*"
      - "screenshots"
    when: always

