variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 4

stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose --release
    - cargo test --verbose
  cache:
    paths:
      - target/
  artifacts:
    paths:
      - target/release/bernardo
    expire_in: 30 days

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose --release
    - cargo test --verbose