[package]
name = "bernardo"
version = "0.1.0"
authors = ["Andrzej J Skalski <gitstuff@s5i.ch>"]
edition = "2018"
license = "GPLv3"

[dependencies]
log = "0.4.14"
crossbeam-channel = "0.5.1"
termion = "1.5.6"
unicode-segmentation = "1.6.0"
unicode-width = "0.1.8"
env_logger = "0.9.0"
ropey = "1.3.1"
filesystem = "0.4.4"