[package]
name = "bernardo"
version = "0.1.0"
authors = ["Andrzej J Skalski <gitstuff@s5i.ch>"]
edition = "2018"
license = "GPLv3"

[dependencies]
log = "0.4.14"
crossbeam-channel = "0.5.1"
termion = "1.5.6"
unicode-segmentation = "1.6.0"
unicode-width = "0.1.8"
ropey = "1.3.1"
stderrlog = "0.5.1"
filesystem = "0.4.4"
crossterm = "0.22.1"
either = "1.6.1"
tree-sitter = "0.20.2"

[profile.dev]
opt-level = 0
debug = 2
lto = false

#https://github.com/tree-sitter/tree-sitter/tree/master/lib/binding_rust
[build-dependencies]
cc = "*"