[package]
name = "bernardo"
version = "0.1.0"
authors = ["Andrzej J Skalski <gitstuff@s5i.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
