[package]
name = "bernardo"
version = "0.1.0"
authors = ["Andrzej J Skalski <gitstuff@s5i.ch>"]
edition = "2018"
license = "GPLv3"

[dependencies]
clap = "3.0.13"
clap-verbosity-flag = "0.4.1"
log = "0.4.14"
crossbeam-channel = "0.5.1"
termion = "1.5.6"
unicode-segmentation = "1.6.0"
unicode-width = "0.1.8"
ropey = "1.3.1"
filesystem = "0.4.4"
crossterm = "0.23.0"
either = "1.6.1"
env_logger = "0.9.0"
json = "0.12.4"
ron = "0.7.0"
serde = { version = "1", features = ["derive"] }
hex = "0.4.3"
syntect = "4.6.0"
simsearch = "0.2.3"
ignore = "0.4.18"
num = "0.4.0"
arboard = "2.1.0"
streaming-iterator = "0.1.5"

maplit = "1.0.2"
lazy_static = "1.4.0"
matches = "0.1.9"

#tree sitter items
tree-sitter = "0.20.2"
tree-sitter-c = "0.20.1"
tree-sitter-cpp = "0.20.0"
tree-sitter-elm = "5.5.1"
tree-sitter-go = "0.19.1"
tree-sitter-html = "0.19.0"
tree-sitter-rust = "0.20.1"
#TODO add more

[profile.dev]
opt-level = 0
debug = 2
lto = false

#https://github.com/tree-sitter/tree-sitter/tree/master/lib/binding_rust
[build-dependencies]
cc = { version = "*", features = ["parallel"] }