name: Everything
on: [ push ]

jobs:
  everything:
    runs-on: docker
    container:
      image: rust:1-bookworm
    steps:
      - name: install prerequisites
        run: |
          apt-get update
          apt-get install -y curl build-essential gcc make clangd clang nodejs
          rustup component add rustfmt
          rustup component add rust-analyzer      
          curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - name: check versions
        run: |
          cargo --version
          which rust-analyzer
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: build
        run: cargo build
      - name: test
        run: cargo nextest run --no-fail-fast --retries 4
      - name: check-fmt
        run: cargo fmt --check