image: debian/stable
packages:
  - git
sources:
  - https://git.sr.ht/~njskalski/bernardo
tasks:
  - setup: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - build: |
      cd bernardo
      cargo build