image: rust:bullseye
packages:
  - git
sources:
  - https://git.sr.ht/~njskalski/bernardo
tasks:
  - setup: |
      rustup component add rust-analyzer
      sudo apt update
      sudo apt install -y clangd clang
  - build: |
      cd bernardo
      cargo build
  - test: |
      cd bernardo
      cargo test
  - check_format: |
      cd bernardo
      cargo fmt --check